[package]
name = "subspace-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-trait = "0.1"
bytesize = "1.1"
dirs = "4"
either = "1.8"
futures = "0.3"
libp2p-core = "0.34"
tempdir = "0.3"
thiserror = "1"
tokio = { version = "1.21", features = ["rt"] }

sc-consensus-slots = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "1a7c28721fa77ecce9632ad9ce473f2d3cf1a598" }
sc-chain-spec = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "1a7c28721fa77ecce9632ad9ce473f2d3cf1a598" }
sc-executor = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "1a7c28721fa77ecce9632ad9ce473f2d3cf1a598", features = ["wasmtime"] }
sc-network = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "1a7c28721fa77ecce9632ad9ce473f2d3cf1a598" }
sc-service = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "1a7c28721fa77ecce9632ad9ce473f2d3cf1a598", default-features = false, features = ["wasmtime"] }

sc-subspace-chain-specs = { git = "https://github.com/subspace/subspace", rev = "c3a4eee7c72ebd65ca6cbc63c3aad661e4411fe5" }
subspace-archiving = { git = "https://github.com/subspace/subspace", rev = "c3a4eee7c72ebd65ca6cbc63c3aad661e4411fe5" }
subspace-core-primitives = { git = "https://github.com/subspace/subspace", rev = "c3a4eee7c72ebd65ca6cbc63c3aad661e4411fe5" }
subspace-farmer = { git = "https://github.com/subspace/subspace", rev = "c3a4eee7c72ebd65ca6cbc63c3aad661e4411fe5" }
subspace-fraud-proof = { git = "https://github.com/subspace/subspace", rev = "c3a4eee7c72ebd65ca6cbc63c3aad661e4411fe5" }
subspace-networking = { git = "https://github.com/subspace/subspace", rev = "c3a4eee7c72ebd65ca6cbc63c3aad661e4411fe5" }
subspace-node = { git = "https://github.com/subspace/subspace", rev = "c3a4eee7c72ebd65ca6cbc63c3aad661e4411fe5" }
subspace-rpc-primitives = { git = "https://github.com/subspace/subspace", rev = "c3a4eee7c72ebd65ca6cbc63c3aad661e4411fe5" }
subspace-runtime = { git = "https://github.com/subspace/subspace", rev = "c3a4eee7c72ebd65ca6cbc63c3aad661e4411fe5" }
subspace-service = { git = "https://github.com/subspace/subspace", rev = "c3a4eee7c72ebd65ca6cbc63c3aad661e4411fe5" }
system-domain-runtime = { git = "https://github.com/subspace/subspace", rev = "c3a4eee7c72ebd65ca6cbc63c3aad661e4411fe5" }

[dev-dependencies]
tokio = { version = "1.21", features = ["rt-multi-thread", "macros"] }

[patch.crates-io]
# TODO: Remove once chacha20poly1305 0.10 appears in libp2p's dependencies
chacha20poly1305 = { git = "https://github.com/RustCrypto/AEADs", rev = "06dbfb5571687fd1bbe9d3c9b2193a1ba17f8e99" }
libp2p = { git = "https://github.com/subspace/rust-libp2p", branch = "subspace-v3" }
