[package]
name = "subspace-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-trait = "0.1"
backoff = "0.4"
base58 = "0.2"
blake2 = "0.10.5"
bytesize = "1.1"
bytesize-serde = "0.2"
derivative = "2.2.0"
derive_builder = "0.12"
derive_more = "0.99"
either = "1.8"
event-listener-primitives = "2.0.1"
futures = "0.3"
jsonrpsee-core = "0.16"
libp2p-core = "0.38"
lru = "0.8"
names = { version = "0.14.0", default-features = false }
ouroboros = "0.15.5"
parity-db = "0.4"
parking_lot = "0.12"
pin-project = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ss58-registry = "1.33"
thiserror = "1"
tokio = { version = "1.25", features = ["fs", "rt"] }
tokio-stream = { version = "0.1", features = ["sync", "time"] }
tracing = "0.1"
tracing-futures = "0.2"

frame-support = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
frame-system-rpc-runtime-api = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
pallet-transaction-payment-rpc-runtime-api = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sc-chain-spec = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sc-client-api = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sc-consensus-slots = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sc-executor = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sc-network = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sc-network-common = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sc-rpc = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sc-rpc-api = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sc-service = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34", default-features = false }
sc-state-db = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sc-telemetry = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sc-utils = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sp-api = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sp-block-builder = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sp-blockchain = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sp-consensus = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sp-core = { version = "7.0.0", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sp-offchain = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sp-runtime = { version = "7.0.0", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sp-session = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sp-transaction-pool = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }
sp-version = { version = "5.0.0", git = "https://github.com/subspace/substrate", rev = "100d6c90d4122578006a47c1dcaf155b9c685f34" }

core-payments-domain-runtime = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
cross-domain-message-gossip = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
domain-client-message-relayer = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
domain-runtime-primitives = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
domain-service = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
sc-consensus-subspace = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
sc-consensus-subspace-rpc = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
sc-subspace-chain-specs = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
sp-consensus-subspace = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
sp-domains = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
sp-objects = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
subspace-archiving = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
subspace-core-primitives = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
subspace-farmer = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
subspace-farmer-components = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
subspace-fraud-proof = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
subspace-networking = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
subspace-transaction-pool = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
subspace-rpc-primitives = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
subspace-runtime = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
subspace-runtime-primitives = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
subspace-service = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }
system-domain-runtime = { git = "https://github.com/subspace/subspace", rev = "eea00c18f5ddde91ad81f916bfe1f13795868019" }

[dev-dependencies]
clap = { version = "4", features = ["derive"] }
tempfile = "3.3"
tokio = { version = "1.21", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = "0.3"

[patch.crates-io]
# TODO: Remove once chacha20poly1305 0.10 appears in libp2p's dependencies
chacha20poly1305 = { git = "https://github.com/RustCrypto/AEADs", rev = "06dbfb5571687fd1bbe9d3c9b2193a1ba17f8e99" }

# The list of dependencies below (which can be both direct and indirect dependencies) are crates
# that are suspected to be CPU-intensive, and that are unlikely to require debugging (as some of
# their debug info might be missing) or to require to be frequently recompiled. We compile these
# dependencies with `opt-level=3` even in "dev" mode in order to make "dev" mode more usable.
# The majority of these crates are cryptographic libraries.
#
# This list is ordered alphabetically.
[profile.dev.package]
ark-bls12-381 = { opt-level = 3 }
ark-ec = { opt-level = 3 }
ark-ff = { opt-level = 3 }
ark-ff-asm = { opt-level = 3 }
ark-poly = { opt-level = 3 }
ark-serialize = { opt-level = 3 }
ark-std = { opt-level = 3 }
blake2 = { opt-level = 3 }
blake2b_simd = { opt-level = 3 }
chacha20poly1305 = { opt-level = 3 }
cranelift-codegen = { opt-level = 3 }
cranelift-wasm = { opt-level = 3 }
crc32fast = { opt-level = 3 }
crossbeam-deque = { opt-level = 3 }
crypto-mac = { opt-level = 3 }
curve25519-dalek = { opt-level = 3 }
dusk-bls12_381 = { opt-level = 3 }
dusk-plonk = { opt-level = 3 }
ed25519-zebra = { opt-level = 3 }
flate2 = { opt-level = 3 }
futures-channel = { opt-level = 3 }
hashbrown = { opt-level = 3 }
hash-db = { opt-level = 3 }
hmac = { opt-level = 3 }
httparse = { opt-level = 3 }
integer-sqrt = { opt-level = 3 }
k256 = { opt-level = 3 }
keccak = { opt-level = 3 }
libm = { opt-level = 3 }
libsecp256k1 = { opt-level = 3 }
libz-sys = { opt-level = 3 }
mio = { opt-level = 3 }
nalgebra = { opt-level = 3 }
num-bigint = { opt-level = 3 }
parking_lot = { opt-level = 3 }
parking_lot_core = { opt-level = 3 }
percent-encoding = { opt-level = 3 }
primitive-types = { opt-level = 3 }
reed-solomon-erasure = { opt-level = 3 }
ring = { opt-level = 3 }
rustls = { opt-level = 3 }
secp256k1 = { opt-level = 3 }
sha2 = { opt-level = 3 }
sha3 = { opt-level = 3 }
smallvec = { opt-level = 3 }
snow = { opt-level = 3 }
subspace-core-primitives = { opt-level = 3 }
subspace-archiving = { opt-level = 3 }
twox-hash = { opt-level = 3 }
uint = { opt-level = 3 }
wasmi = { opt-level = 3 }
x25519-dalek = { opt-level = 3 }
yamux = { opt-level = 3 }
zeroize = { opt-level = 3 }

