[package]
name = "subspace-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-trait = "0.1"
base58 = "0.2"
blake2-rfc = "0.2"
bytesize = "1.1"
derive_more = "0.99"
futures = "0.3"
jsonrpsee-core = "0.15.1"
libp2p-core = "0.34"
serde = "1"
ss58-registry = "1.33"
thiserror = "1"
tokio = { version = "1.21", features = ["fs", "rt"] }
tokio-stream = { version = "0.1", features = ["sync"] }

frame-support = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "1a7c28721fa77ecce9632ad9ce473f2d3cf1a598" }
sc-chain-spec = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "1a7c28721fa77ecce9632ad9ce473f2d3cf1a598" }
sc-consensus-slots = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "1a7c28721fa77ecce9632ad9ce473f2d3cf1a598" }
sc-executor = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "1a7c28721fa77ecce9632ad9ce473f2d3cf1a598", features = ["wasmtime"] }
sc-network = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "1a7c28721fa77ecce9632ad9ce473f2d3cf1a598" }
sc-service = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "1a7c28721fa77ecce9632ad9ce473f2d3cf1a598", default-features = false, features = ["wasmtime"] }
sp-consensus = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "1a7c28721fa77ecce9632ad9ce473f2d3cf1a598" }
sc-telemetry = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "1a7c28721fa77ecce9632ad9ce473f2d3cf1a598" }
sc-client-api = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "1a7c28721fa77ecce9632ad9ce473f2d3cf1a598" }
sp-blockchain = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "1a7c28721fa77ecce9632ad9ce473f2d3cf1a598" }
sp-core = { version = "6.0.0", git = "https://github.com/subspace/substrate", rev = "1a7c28721fa77ecce9632ad9ce473f2d3cf1a598" }
sp-runtime = { version = "6.0.0", git = "https://github.com/subspace/substrate", rev = "1a7c28721fa77ecce9632ad9ce473f2d3cf1a598" }

sc-consensus-subspace-rpc = { git = "https://github.com/subspace/subspace", rev = "28cda68b9c07851f42f007693a238fc3fe80406c" }
sc-subspace-chain-specs = { git = "https://github.com/subspace/subspace", rev = "28cda68b9c07851f42f007693a238fc3fe80406c" }
sp-consensus-subspace = { git = "https://github.com/subspace/subspace", rev = "28cda68b9c07851f42f007693a238fc3fe80406c" }
sp-domains = { git = "https://github.com/subspace/subspace", rev = "28cda68b9c07851f42f007693a238fc3fe80406c" }
subspace-archiving = { git = "https://github.com/subspace/subspace", rev = "28cda68b9c07851f42f007693a238fc3fe80406c" }
subspace-core-primitives = { git = "https://github.com/subspace/subspace", rev = "28cda68b9c07851f42f007693a238fc3fe80406c" }
subspace-farmer = { git = "https://github.com/subspace/subspace", rev = "28cda68b9c07851f42f007693a238fc3fe80406c" }
subspace-fraud-proof = { git = "https://github.com/subspace/subspace", rev = "28cda68b9c07851f42f007693a238fc3fe80406c" }
subspace-networking = { git = "https://github.com/subspace/subspace", rev = "28cda68b9c07851f42f007693a238fc3fe80406c" }
subspace-rpc-primitives = { git = "https://github.com/subspace/subspace", rev = "28cda68b9c07851f42f007693a238fc3fe80406c" }
subspace-runtime = { git = "https://github.com/subspace/subspace", rev = "28cda68b9c07851f42f007693a238fc3fe80406c" }
subspace-runtime-primitives = { git = "https://github.com/subspace/subspace", rev = "28cda68b9c07851f42f007693a238fc3fe80406c" }
subspace-service = { git = "https://github.com/subspace/subspace", rev = "28cda68b9c07851f42f007693a238fc3fe80406c" }
system-domain-runtime = { git = "https://github.com/subspace/subspace", rev = "28cda68b9c07851f42f007693a238fc3fe80406c" }

[dev-dependencies]
tempdir = "0.3"
tokio = { version = "1.21", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[patch.crates-io]
# TODO: Remove once chacha20poly1305 0.10 appears in libp2p's dependencies
chacha20poly1305 = { git = "https://github.com/RustCrypto/AEADs", rev = "06dbfb5571687fd1bbe9d3c9b2193a1ba17f8e99" }
libp2p = { git = "https://github.com/subspace/rust-libp2p", branch = "subspace-v3" }

# The list of dependencies below (which can be both direct and indirect dependencies) are crates
# that are suspected to be CPU-intensive, and that are unlikely to require debugging (as some of
# their debug info might be missing) or to require to be frequently recompiled. We compile these
# dependencies with `opt-level=3` even in "dev" mode in order to make "dev" mode more usable.
# The majority of these crates are cryptographic libraries.
#
# This list is ordered alphabetically.
[profile.dev.package]
blake2 = { opt-level = 3 }
blake2-rfc = { opt-level = 3 }
blake2b_simd = { opt-level = 3 }
chacha20poly1305 = { opt-level = 3 }
cranelift-codegen = { opt-level = 3 }
cranelift-wasm = { opt-level = 3 }
crc32fast = { opt-level = 3 }
crossbeam-deque = { opt-level = 3 }
crypto-mac = { opt-level = 3 }
curve25519-dalek = { opt-level = 3 }
dusk-bls12_381 = { opt-level = 3 }
dusk-plonk = { opt-level = 3 }
ed25519-dalek = { opt-level = 3 }
flate2 = { opt-level = 3 }
futures-channel = { opt-level = 3 }
hashbrown = { opt-level = 3 }
hash-db = { opt-level = 3 }
hmac = { opt-level = 3 }
httparse = { opt-level = 3 }
integer-sqrt = { opt-level = 3 }
keccak = { opt-level = 3 }
libm = { opt-level = 3 }
libsecp256k1 = { opt-level = 3 }
libz-sys = { opt-level = 3 }
mio = { opt-level = 3 }
nalgebra = { opt-level = 3 }
num-bigint = { opt-level = 3 }
parking_lot = { opt-level = 3 }
parking_lot_core = { opt-level = 3 }
percent-encoding = { opt-level = 3 }
primitive-types = { opt-level = 3 }
reed-solomon-erasure = { opt-level = 3 }
ring = { opt-level = 3 }
rustls = { opt-level = 3 }
sha2 = { opt-level = 3 }
sha3 = { opt-level = 3 }
smallvec = { opt-level = 3 }
snow = { opt-level = 3 }
subspace-core-primitives = { opt-level = 3 }
subspace-archiving = { opt-level = 3 }
twox-hash = { opt-level = 3 }
uint = { opt-level = 3 }
wasmi = { opt-level = 3 }
x25519-dalek = { opt-level = 3 }
yamux = { opt-level = 3 }
zeroize = { opt-level = 3 }
