[package]
name = "sdk-dsn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-trait = "0.1"
derivative = "2.2.0"
derive_builder = "0.12"
derive_more = "0.99"
either = "1.8"
hex = "0.4.3"
parking_lot = "0.12"
futures = "0.3"
tokio = { version = "1.26", features = ["fs", "rt", "tracing"] }
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
ouroboros = "0.15.5"
sdk-utils = { path = "../utils" }

sc-client-api = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
sp-runtime = { version = "7.0.0", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
sp-blockchain = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }

subspace-networking = { git = "https://github.com/subspace/subspace", rev = "582b73e5505fe4e4f9bb41b3f867df2d76ed6be4" }
subspace-core-primitives = { git = "https://github.com/subspace/subspace", rev = "582b73e5505fe4e4f9bb41b3f867df2d76ed6be4" }
subspace-farmer = { git = "https://github.com/subspace/subspace", rev = "582b73e5505fe4e4f9bb41b3f867df2d76ed6be4" }
subspace-farmer-components = { git = "https://github.com/subspace/subspace", rev = "582b73e5505fe4e4f9bb41b3f867df2d76ed6be4" }
subspace-service = { git = "https://github.com/subspace/subspace", rev = "582b73e5505fe4e4f9bb41b3f867df2d76ed6be4" }
sc-consensus-subspace = { git = "https://github.com/subspace/subspace", rev = "582b73e5505fe4e4f9bb41b3f867df2d76ed6be4" }
