[package]
name = "sdk-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
backoff = "0.4"
derivative = "2.2.0"
derive_builder = "0.12"
derive_more = "0.99"
futures = "0.3"
hex-literal = "0.4"
parity-scale-codec = "3"
parking_lot = "0.12"
pin-project = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
static_assertions = "1.1.0"
tokio = { version = "1.26", features = ["fs", "rt", "tracing"] }
tokio-stream = { version = "0.1", features = ["sync", "time"] }
tracing = "0.1"
tracing-futures = "0.2"
sdk-utils = { path = "../utils" }
sdk-dsn = { path = "../dsn" }
sdk-substrate = { path = "../substrate" }
sdk-traits = { path = "../traits" }

frame-support = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
frame-system = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
frame-system-rpc-runtime-api = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
pallet-transaction-payment-rpc-runtime-api = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
sc-chain-spec = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
sc-client-api = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
sc-consensus-slots = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
sc-executor = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
sc-network = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
sc-network-sync = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
sc-rpc-api = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
sc-service = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30", default-features = false }
sc-storage-monitor = { version = "0.1.0", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30", default-features = false }
sc-telemetry = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
sp-api = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
sp-block-builder = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
sp-blockchain = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
sp-consensus = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
sp-core = { version = "7.0.0", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
sp-offchain = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
sp-runtime = { version = "7.0.0", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
sp-session = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
sp-transaction-pool = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
sp-version = { version = "5.0.0", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }

core-eth-relay-runtime = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be", optional = true }
core-evm-runtime = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be", optional = true }
core-payments-domain-runtime = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be", optional = true }
cross-domain-message-gossip = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be" }
domain-client-executor = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be" }
domain-eth-service = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be", optional = true }
domain-runtime-primitives = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be" }
domain-service = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be" }
pallet-rewards = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be" }
pallet-subspace = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be" }
sc-consensus-subspace-rpc = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be" }
sc-subspace-chain-specs = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be" }
sp-consensus-subspace = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be" }
sp-domains = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be" }
sp-messenger = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be" }
subspace-core-primitives = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be" }
subspace-farmer = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be" }
subspace-farmer-components = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be" }
subspace-networking = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be" }
subspace-runtime = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be" }
subspace-runtime-primitives = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be" }
subspace-service = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be" }
subspace-transaction-pool = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be" }
system-domain-runtime = { git = "https://github.com/subspace/subspace", rev = "2bc2fde2765cfa1b06cac0861ed880305792c4be", optional = true }

fp-evm = { version = "3.0.0-dev", git = "https://github.com/subspace/frontier/", rev = "e60f3f8617cabd3473bd5e197b7c0c1991fbcd9b", optional = true }

[features]
default = ["all"]
all = ["executor", "eth-relayer", "core-payments", "core-evm"]
executor = ["system-domain-runtime"]
eth-relayer = ["core-eth-relay-runtime"]
core-payments = ["core-payments-domain-runtime"]
core-evm = ["core-evm-runtime", "domain-eth-service", "fp-evm"]
