[package]
name = "sdk-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-trait = "0.1"
base58 = "0.2"
blake2 = "0.10.5"
bytesize = "1"
bytesize-serde = "0.2"
derivative = "2.2.0"
derive_more = "0.99"
futures = "0.3"
jsonrpsee-core = "0.16"
libp2p-core = "0.39"
parity-scale-codec = "3"
serde = { version = "1", features = ["derive"] }
ss58-registry = "1.33"
thiserror = "1"
tokio = { version = "1", features = ["rt", "tracing"] }

frame-support = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "88bb945975301f9b29bad96dc4590c33f1029eae" }
frame-system = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "88bb945975301f9b29bad96dc4590c33f1029eae" }
sc-service = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "88bb945975301f9b29bad96dc4590c33f1029eae", default-features = false }
sc-rpc = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "88bb945975301f9b29bad96dc4590c33f1029eae", default-features = false }
sc-rpc-api = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "88bb945975301f9b29bad96dc4590c33f1029eae", default-features = false }
sc-network = { version = "0.10.0-dev", git = "https://github.com/subspace/substrate", rev = "88bb945975301f9b29bad96dc4590c33f1029eae", default-features = false }
sp-core = { version = "7.0.0", git = "https://github.com/subspace/substrate", rev = "88bb945975301f9b29bad96dc4590c33f1029eae" }
sp-core-hashing = { version = "5.0.0", git = "https://github.com/subspace/substrate", rev = "88bb945975301f9b29bad96dc4590c33f1029eae" }
sp-runtime = { version = "7.0.0", git = "https://github.com/subspace/substrate", rev = "88bb945975301f9b29bad96dc4590c33f1029eae" }
sp-storage = { version = "7.0.0", git = "https://github.com/subspace/substrate", rev = "88bb945975301f9b29bad96dc4590c33f1029eae" }

sc-consensus-subspace-rpc = { git = "https://github.com/subspace/subspace", rev = "62602ac631189346b02a47398b77f0f5cceb287e" }
subspace-archiving = { git = "https://github.com/subspace/subspace", rev = "62602ac631189346b02a47398b77f0f5cceb287e" }
subspace-farmer = { git = "https://github.com/subspace/subspace", rev = "62602ac631189346b02a47398b77f0f5cceb287e" }
subspace-rpc-primitives = { git = "https://github.com/subspace/subspace", rev = "62602ac631189346b02a47398b77f0f5cceb287e" }
subspace-runtime = { git = "https://github.com/subspace/subspace", rev = "62602ac631189346b02a47398b77f0f5cceb287e" }
subspace-runtime-primitives = { git = "https://github.com/subspace/subspace", rev = "62602ac631189346b02a47398b77f0f5cceb287e" }

# Unused for now. TODO: add `serde` feature to `subspace-core-primitives` in `subspace-archiver`
subspace-core-primitives = { git = "https://github.com/subspace/subspace", rev = "62602ac631189346b02a47398b77f0f5cceb287e" }
