[package]
name = "sdk-traits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
parking_lot = "0.12"
sdk-dsn = { path = "../dsn" }

subspace-core-primitives = { git = "https://github.com/subspace/subspace", rev = "0ffe8652edcfc495e44eed861db44d730237bbd2" }
subspace-farmer = { git = "https://github.com/subspace/subspace", rev = "0ffe8652edcfc495e44eed861db44d730237bbd2" }
subspace-farmer-components = { git = "https://github.com/subspace/subspace", rev = "0ffe8652edcfc495e44eed861db44d730237bbd2" }
subspace-proof-of-space = { git = "https://github.com/subspace/subspace", rev = "0ffe8652edcfc495e44eed861db44d730237bbd2" }

sc-client-api = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "9cf78129a2638d3f370868863d16f4fe32b4ad30" }
