[package]
name = "sdk-traits"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
parking_lot = "0.12"
sc-client-api = { version = "4.0.0-dev", git = "https://github.com/subspace/polkadot-sdk", rev = "892bf8e938c6bd2b893d3827d1093cd81baa59a1" }
sdk-dsn = { path = "../dsn" }
subspace-core-primitives = { git = "https://github.com/subspace/subspace", rev = "dd2a264b0b7747793765d5436b0df5cdcc0e12cd" }
subspace-farmer = { git = "https://github.com/subspace/subspace", rev = "dd2a264b0b7747793765d5436b0df5cdcc0e12cd" }
subspace-proof-of-space = { git = "https://github.com/subspace/subspace", rev = "dd2a264b0b7747793765d5436b0df5cdcc0e12cd" }

[features]
default = []
integration-test = [
    "sdk-dsn/integration-test"
]
