[package]
name = "sdk-traits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
parking_lot = "0.12"
sdk-dsn = { path = "../dsn" }

subspace-core-primitives = { git = "https://github.com/subspace/subspace", rev = "814ca7a223dafde52612ce9acee837a75c6661c7" }
subspace-farmer = { git = "https://github.com/subspace/subspace", rev = "814ca7a223dafde52612ce9acee837a75c6661c7" }
subspace-farmer-components = { git = "https://github.com/subspace/subspace", rev = "814ca7a223dafde52612ce9acee837a75c6661c7" }
subspace-proof-of-space = { git = "https://github.com/subspace/subspace", rev = "814ca7a223dafde52612ce9acee837a75c6661c7" }

sc-client-api = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "28e33f78a3aa8ac4c6753108bc0471273ff6bf6f" }
