name: Rust checks and tests
on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
  workflow_dispatch:
    inputs:
      test-macos:
        description: 'Whether to run macOS tests'
        required: true
        default: false
        type: boolean

concurrency:
  group: push-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Not needed in CI, should make things a bit faster
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  MAX_TARGET_SIZE: 1024 # MB
  RUSTFLAGS: -C debuginfo=0 --cfg tokio_unstable

jobs:
  test:
    strategy:
      matrix:
        os:
          - windows-2022
        run-all:
          - ${{ inputs.test-macos || github.ref == 'refs/heads/master' }}
        exclude:  # exclude macos-12 when the condition is false
          - run-all: false
            os: macos-12

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Install Protoc
        uses: arduino/setup-protoc@64c0c85d18e984422218383b81c52f8b077404d3 # v1.1.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@8852e4d5c58653ed05135c0a5d949d9c2febcb00 # v1.6.1
        with:
          version: "15.0"

      # Workaround to resolve link error with C:\msys64\mingw64\bin\libclang.dll
      - name: Remove msys64
        run: Remove-Item -LiteralPath "C:\msys64\" -Force -Recurse
        if: runner.os == 'Windows'

      - name: Build and run tests
        run: cargo test --locked --test integration --release -- --test-threads=1 --nocapture node_events

  test_2:
    strategy:
      matrix:
        os:
          - windows-2022
        run-all:
          - ${{ inputs.test-macos || github.ref == 'refs/heads/master' }}
        exclude:  # exclude macos-12 when the condition is false
          - run-all: false
            os: macos-12

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Install Protoc
        uses: arduino/setup-protoc@64c0c85d18e984422218383b81c52f8b077404d3 # v1.1.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@8852e4d5c58653ed05135c0a5d949d9c2febcb00 # v1.6.1
        with:
          version: "15.0"

      # Workaround to resolve link error with C:\msys64\mingw64\bin\libclang.dll
      - name: Remove msys64
        run: Remove-Item -LiteralPath "C:\msys64\" -Force -Recurse
        if: runner.os == 'Windows'

      - name: Build and run tests
        run: cargo test --locked --test integration --release -- --test-threads=1 --nocapture fetch_block_author
