on: push
name: Rust checks and tests

env:
  # Not needed in CI, should make things a bit faster
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  # Build smaller artifacts to avoid running out of space in CI
  # TODO: Try to remove once https://github.com/paritytech/substrate/issues/11538 is resolved
  RUSTFLAGS: -C strip=symbols -C opt-level=s
  # Remove unnecessary WASM build artefacts
  WASM_BUILD_CLEAN_TARGET: 1

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14.0"

      - name: Configure cache
        uses: Swatinem/rust-cache@v2

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14.0"

      - name: Configure cache
        uses: Swatinem/rust-cache@v2

      - run: cargo test
