name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    if: github.repository == 'subspace/subspace-sdk' && (github.repository_owner == 'subspace' || contains(github.event.repository.collaborators, github.actor))
    runs-on: ["self-hosted", "ubuntu-20.04-x86-64", "Linux"]
    steps:
      - name: git checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - uses: taiki-e/create-gh-release-action@426f7d3b286dc631e7361a1738e1d2f7418b7f01 # v1.6.1
        with:
          changelog: CHANGELOG.md
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
