name: rustdoc

on:
  push:
   branches:
   - master

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  rustdoc:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14.0"

      # Build the rust crate docs
      # Use `RUSTC_BOOTSTRAP` in order to use the `--enable-index-page` flag of rustdoc
      # This is needed in order to generate a landing page `index.html` for workspaces
      - name: Build Documentation
        run: cargo doc --all --no-deps --lib
        env:
          RUSTC_BOOTSTRAP: 1
          RUSTDOCFLAGS: "-Z unstable-options --enable-index-page"

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/doc
