name: rustdoc

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.gitignore'

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  rustdoc:
    if: github.repository == 'subspace/subspace-sdk' && (github.repository_owner == 'subspace' || contains(github.event.repository.collaborators, github.actor))
    runs-on: ["self-hosted", "ubuntu-22.04-x86-64", "Linux"]

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        if: runner.os == 'Linux'

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@8852e4d5c58653ed05135c0a5d949d9c2febcb00 # v1.6.1
        with:
          version: "15.0"

      # Build the rust crate docs
      # Use `RUSTC_BOOTSTRAP` in order to use the `--enable-index-page` flag of rustdoc
      # This is needed in order to generate a landing page `index.html` for workspaces

      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly-2023-05-16
            components: rustfmt, clippy, rust-src, rust-std

      - name: Build Documentation
        run: cargo doc --all --no-deps --lib
        env:
          RUSTC_BOOTSTRAP: 1
          RUSTDOCFLAGS: "-Z unstable-options --enable-index-page"

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@ba1486788b0490a235422264426c45848eac35c6 # v4.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/doc
